# Generated by Django 3.2.5 on 2021-11-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_project_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='documents',
        ),
    ]
